version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-ms
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-ms
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "trade_events:1:1,trade_events_consumed:1:1,trade_events_errors:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-ms
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all
    volumes:
      - mongodb_data:/data/db
    networks:
      - kafka-network

  redis:
    image: redis:latest
    container_name: redis-ms
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: