version: '3.8'

services:
  kafka-trade-consumer:
    build: ./kafka_trade_consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: trade_events
      KAFKA_GROUP_ID: trade_consumer_group
      KAFKA_DLQ_TOPIC: trade_events_errors
      KAFKA_PROCESSED_TOPIC: trade_events_consumed
    networks:
      - kafka-network

  event-processing-service:
    build: ./event_processing_service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: trade_events_consumed
      KAFKA_GROUP_ID: event_processing_group
      MONGO_URI: mongodb://mongodb:27017/realtime
      MONGO_COLLECTION: trade_events
    networks:
      - kafka-network

  metrics-service:
    build: ./metrics_service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MONGO_URI: mongodb://mongodb:27017/realtime
      MONGO_COLLECTION: trade_events
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
