apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-processing-service
  template:
    metadata:
      labels:
        app: event-processing-service
    spec:
      containers:
      - name: event-processing-service
        image: event-processing-service:v10
        imagePullPolicy: Never
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "trade_events_consumed"
        - name: KAFKA_GROUP_ID
          value: "event_processing_group"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/realtime"
        - name: MONGO_COLLECTION
          value: "trade_events"
