apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: NodePort
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: external
      port: 30092
      targetPort: 30092
      nodePort: 30092
  selector:
    app: kafka
