apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-trade-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-trade-consumer
  template:
    metadata:
      labels:
        app: kafka-trade-consumer
    spec:
      containers:
      - name: kafka-trade-consumer
        image: kafka-trade-consumer:v2
        imagePullPolicy: Never
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "trade_events"
        - name: KAFKA_GROUP_ID
          value: "trade_consumer_group"
        - name: KAFKA_DLQ_TOPIC
          value: "trade_events_errors"
        - name: KAFKA_PROCESSED_TOPIC
          value: "trade_events_consumed"
